### PR TITLE
Replace typing overloads with a functools.wraps declaration.

### PR DESCRIPTION
**Pull request by jaraco**

### CODE REVIEW

**Comment by jaraco** [comment]
@bswck in https://github.com/jaraco/path/pull/224#issuecomment-2048236055 noted that this technique does in fact appear to do the right thing when types are validated with pylance, but not so much with mypy. That's actually pretty encouraging and suggests that may be the best approach for a library like this - to signal the intent and let the typing systems catch up. Especially if mypy is tracking this issue and has plans to implement it, I'd say that's good enough....

**Comment by jaraco** [comment]
https://github.com/python/mypy/issues/10574 appears to be related. https://github.com/python/mypy/issues/12573 suggests that mypy may be philosophically opposed to dynamic behavior.

**Comment by bswck** [comment]
I ended up with the silliest

```py
open = open
```

being a working solution in both mypy and pylance. The doc is however copied entirely from `builtins.open` then.

**Comment by bswck** [comment]
> > The doc is however copied entirely from `builtins.open` then
> 
> I suspect (and confirmed) that's also the case for `functools.wraps(open)`, as that's part of what `wraps` does. The `__doc__` could probably be retained by passing more parameters to `functools.wraps` (namely, passing the defaults minus `__doc__`), but that's unlikely to be elegant.

Yeah, it can be retained by `assigned=tuple(set(functools.WRAPPER_ASSIGNMENTS) - {"__doc__"})` as I think about it rn.

**Comment by bswck** [comment]
It would be more useful for `functools.wraps()` to receive a parameter with attributes to skip. I'll try to suggest that in the Python community.

**Comment by jaraco** [comment]
> It would be more useful for `functools.wraps()` to receive a parameter with attributes to skip. I'll try to suggest that in the Python community.

I wonder, though, if in this case, `assigned=()` would be the right thing to do.

**Comment by jaraco** [comment]
I've not used pylance. I have VSCode and I see Pylance warnings, but I'm unsure how to elicit the output of `reveal_type`.

**Comment by bswck** [comment]
> > It would be more useful for `functools.wraps()` to receive a parameter with attributes to skip. I'll try to suggest that in the Python community.
> 
> I wonder, though, if in this case, `assigned=()` would be the right thing to do.

Definitely this or `('__annotations__',)`, but I think the latter might be pretty enigmatic for others.

**Comment by bswck** [comment]
> > > It would be more useful for `functools.wraps()` to receive a parameter with attributes to skip. I'll try to suggest that in the Python community.
> > 
> > 
> > I wonder, though, if in this case, `assigned=()` would be the right thing to do.
> 
> Definitely this or `('__annotations__',)`, but I think the latter might be pretty enigmatic for others.

Actually, nevermind. That function doesn't have `__annotations__` so that's a terrible idea 🤦‍♂️

**Review by bswck — APPROVED** [review]

**Comment by jaraco** [comment]
I should have been more cautious about merging this. It breaks on Python 3.11 (only, not 3.10 or 3.12) during test collection:

```
________________________________________________________ ERROR collecting path/__init__.py ________________________________________________________
/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/doctest.py:942: in find
    self._find(tests, obj, name, module, source_lines, globs, {})
/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/doctest.py:1016: in _find
    self._find(tests, val, valname, module, source_lines,
/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/doctest.py:1048: in _find
    self._find(tests, val, valname, module, source_lines,
/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/doctest.py:1004: in _find
    test = self._get_test(obj, name, module, globs, source_lines)
/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/doctest.py:1072: in _get_test
    lineno = self._find_lineno(obj, source_lines)
/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/doctest.py:1121: in _find_lineno
    obj = inspect.unwrap(obj).__code__
E   AttributeError: 'builtin_function_or_method' object has no attribute '__code__'
```

The issue was reported in https://github.com/python/cpython/issues/117692.

**Pull request merged**
