### PR TITLE
Fill in gaps in type annotations.

### LINKED ISSUE #215: Inline the type annotations (if possible)
This project has type annotations defined in .pyi files. Many of these annotations would be useful as inline.

However, due to the "wrapper" nature of this project and the fact that it deals with IO, the type annotations are very complicated, using overloads and providing types for functions that are just aliases.

In [feature/inline-types](https://github.com/jaraco/path/tree/feature/inline-types), I started exploring what it would take to migrate the types. I was hoping to use something like [retype](/ambv/retype), but that project is actively abandoned and has unfixed bugs for things like overloads.

If someone with some expertise would like to work on migrating the types, I'd appreciate the help.

### PR DESCRIPTION
**Pull request by SethMMorton**
This is intended to address issue #234.

It turns out that `mypy` does not look at the annotations in the main `.py` file if a stub `.pyi` file exists. So, functionality added since the `.pyi` files were created that had annotations in-place were not having those annotations exported, resulting in a small subset of functionality missing type hints for this module.

These gaps have been addressed.

The following related changes have also been made:

- Tests now run `mypy.stubtest` to verify that the `.pyi` and `.py` files are in sync, ensuring this does not happen in the future
- Tests now explicitly run `mypy` instead of using the `pytest-mypy` plugin (this plugin was not actually running `mypy`)
- The annotation for `path.Path.joinpath()` has been fixed so that it no longer reports its return type as `Any`

Closes #215

### CODE REVIEW

**Comment by SethMMorton** [comment]
@jaraco Let me know if I have to modify any of my changes to conform to a style guide.

**Comment by jaraco** [comment]
Thanks @SethMMorton for investigating and working on a solution.

> It turns out that `mypy` does not look at the annotations in the main `.py` file if a stub `.pyi` file exists.

My first instinct is that this change takes the project in the wrong direction. Ideally, there should be no need for a stub file and it should be possible to put annotations directly on the code (e.g. https://github.com/jaraco/path/pull/221). The fact that the ecosystem doesn't allow for an incremental transition from a stub file to inline annotations is quite annoying. That seems like a deficiency in mypy and not in this project. In any case, we need to work toward moving all of the annotations out of the stub file and into the source file, and not the reverse.

> * Tests now explicitly run `mypy` instead of using the `pytest-mypy` plugin (this plugin was not actually running `mypy`)

This change is problemmatic. This project builds on [jaraco/skeleton](/jaraco/skeleton) in order to manage systematic concerns across projects in a shared manner (versus applying bespoke maintenance on each project manually). That approach is _intended_ to rely on pytest-mypy to perform type checks. If mypy checks aren't being invoked, that's a bug in the skeleton or elsewhere upstream.

I do see what you're saying - [running tests in verbose mode](https://gist.github.com/jaraco/6f30792d91d6bd9331948ca0b9663927), I don't see mypy running. Looking at pyproject.toml, I see that mypy is disabled due to jaraco/skeleton#143.

I know a lot of progress has been made in getting mypy working again in a number of skeleton-based projects, so it may be time to revert that disablement. Perhaps I'll work on that today.

> * Tests now run `mypy.stubtest` to verify that the `.pyi` and `.py` files are in sync, ensuring this does not happen in the future

Again, this concern is managed at jaraco/skeleton and should avoid diverging from that technique unless there's a very strong reason to do so.

----

Would you be interested instead in working on a PR to migrate the type annotations to source code?

**Comment by jaraco** [comment]
Note that with #233, mypy checks are once again enabled for this project.

**Comment by SethMMorton** [comment]
Sure - I prefer annotations in-source as well. I'll update this PR to remove the stub files and move all annotations in-source.

Just to make sure I understand, I should remove all changes to how `mypy` is invoked because that has been updated upstream?

**Comment by SethMMorton** [comment]
@jaraco OK, here's the re-attempt at this PR. It's pretty different, since the changes are in-source.

The first several commits are directly translating the stub annotations into the in-source annotations. After that are many commits that resolve the mypy errors that result. The attempt was to be atomic with the commits, but if you want me to squash that is OK.

I see that coverage is failing now, likely because of all the platform-dependent branches that were added. I can add no-cover statements if desired.

I also see the docs test is failing... I'll need some guidance there.

**Comment by jaraco** [comment]
> Just to make sure I understand, I should remove all changes to how `mypy` is invoked because that has been updated upstream?

Yes, please.

**Comment by jaraco** [comment]
> I see that coverage is failing now, likely because of all the platform-dependent branches that were added. I can add no-cover statements if desired.

Don't worry about coverage if you haven't changed the coverage profile.

**Comment by jaraco** [comment]
> I also see the docs test is failing... I'll need some guidance there.

The docs errors are caused by `nitpicky = True` in the config. Sphinx tends to be particularly nitpicky about annotation-related work. Just add the relevant things to `nitpick_ignore`. I used Gemini to [extract the relevant lines](https://g.co/gemini/share/c46efad65567).

**Comment by jaraco** [comment]
> The attempt was to be atomic with the commits, but if you want me to squash that is OK.

I'm happy to retain the history of a change (and let the merge commit represent the overall effect).

**Comment by SethMMorton** [comment]
OK - `docs` checks are no longer flagging, thanks for the tip.

**Comment by intel-smmorton** [comment]
I just realized this PR likely resolves https://github.com/jaraco/path/issues/215, correct?

**Comment by SethMMorton** [comment]
I just realized this PR likely resolves #215, correct?

**Pull request merged**
