### PR TITLE
Only supply the overloaded type annotations for .open when type checking.

### PR DESCRIPTION
**Pull request by jaraco**

### CODE REVIEW

**Comment by jaraco** [comment]
Kind of a shame that it takes 331 characters and two new lines and a third level of indentation just to mark these as "not needed at runtime". With this change, I'm now beginning to think these overloads should really be in a stubs file and not inline with the code.

**Comment by bswck** [comment]
As I look at this, it looks pretty overly complex indeed. Let's keep `overload` at runtime if you find that a better option.

**Comment by bswck** [comment]
Actually, I tested `functools.wraps` with this:
Look:
```py
from functools import wraps

class Path:
    @wraps(open)
    def open(self, *args, **kwargs):
        return

reveal_type(Path().open)
```
What a pitty. Pylance gets it right:
<details>
```py
Type of "Path().open" is "_Wrapped[(file: int | str | bytes | PathLike[str] | PathLike[bytes], mode: Literal['r+', '+r', 'rt+', 'r+t', '+rt', 'tr+', 't+r', '+tr', 'w+', '+w', 'wt+', 'w+t', '+wt', 'tw+', 't+w', '+tw', 'a+', '+a', 'at+', 'a+t', '+at', 'ta+', 't+a', '+ta', 'x+', '+x', 'xt+', 'x+t', '+xt', 'tx+', 't+x', '+tx', 'w', 'wt', 'tw', 'a', 'at', 'ta', 'x', 'xt', 'tx', 'r', 'rt', 'tr', 'U', 'rU', 'Ur', 'rtU', 'rUt', 'Urt', 'trU', 'tUr', 'Utr'] = "r", buffering: int = -1, encoding: str | None = None, errors: str | None = None, newline: str | None = None, closefd: bool = True, opener: ((str, int) -> int) | None = None), TextIOWrapper, (self: Path, *args: Any, **kwargs: Any), Any]"Pylance
(method) open: _Wrapped[(file: FileDescriptorOrPath, mode: OpenTextMode = "r", buffering: int = -1, encoding: str | None = None, errors: str | None = None, newline: str | None = None, closefd: bool = True, opener: _Opener | None = None), TextIOWrapper, (self: Path, *args: Any, **kwargs: Any), Any]
```
</details>

But mypy apparently doesn't:

```
t.py:11: note: Revealed type is "def (*args: Any, **kwargs: Any) -> Any"
```
 🤷‍♀️

**Comment by jaraco** [comment]
Superseded by #225.

**Pull request closed without merging**
